swagger:
  enabled: true
  base-package: per
  title: 用户消费者
  description: desc
  license: Wilson
  licenseUrl: https://blog.csdn.net/z28126308
  contact-name: Wilson
  contact-url: https://blog.csdn.net/z28126308
  contact-email: xxx@qq.com
  group-name: ${swagger.title}模块
#  host: http://localhost:${server.port:8080}
  context-path: ${server.context-path:/}
  serviceUrl: ${swagger.host}${server.context-path:}/swagger-ui.html
